### ISSUE TITLE
block sources

### ISSUE THREAD

**Issue by AkakievKD** [argoproj-labs/terraform-provider-argocd#512]
how can make the same in terraform ?

config below is working but i am not sure that i can make the same in terraform

don’t pay attention to the appset type, I’m interested in the sources block

i would like to do this in appset and in simple app
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: billing-account-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - pullRequest:
      gitlab:
        project: '44743534'
        api: https://gitlab.com/
        pullRequestState: opened
        tokenRef:
          secretName: 'gitlab-token-dewac'
          key: token
      requeueAfterSeconds: 5
  template:
    metadata:
      name: 'billing-account-service-{{number}}'
    spec:
      sources:
      - chart: 'kube-state-metrics'
        helm:
          valueFiles:
            - $values-bitnami/Kubernetes/Examlpe of Chart/kube.yaml
        repoURL: 'https://charts.bitnami.com/bitnami'
        targetRevision: 3.3.4
      - chart: 'ingress-nginx'
        helm:
          valueFiles:
            - $values-bitnami/Kubernetes/Examlpe of Chart/nginxingress.yaml
        repoURL: 'https://kubernetes.github.io/ingress-nginx'
        targetRevision: 4.6.0
      - chart: 'nginx'
        helm:
          valueFiles:
            - $values-billing/devops/red/charts/nginx.yaml
        repoURL: 'https://charts.bitnami.com/bitnami'
        targetRevision: 13.2.32
      - repoURL: 'https://gitlab.com/my-projects121/frontend-angular.git'
        targetRevision: 'main'
        ref: values-billing
      - repoURL: 'https://gitlab.com/my-projects121/knowledge-base.git'
        targetRevision: 'main'
        ref: values-bitnami
      project: default
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```

or

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: review-the-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - pullRequest:
      gitlab:
        project: '44743534'
        api: https://gitlab.com/
        pullRequestState: opened
        tokenRef:
          secretName: 'gitlab'
          key: token
      requeueAfterSeconds: 5
  template:
    metadata:
      name: 'review-the-application-{{number}}'
    spec:
      sources:
      - chart: nginx
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 13.2.33
      - chart: ingress-nginx
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: 4.6.0
      project: default
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```
