### ISSUE TITLE
Support elementsYaml for the List generator in the argocd_application_set resource

### ISSUE THREAD

**Issue by aaron-lunsford-even** [argoproj-labs/terraform-provider-argocd#642]
### Description

The [list generator schema](https://registry.terraform.io/providers/argoproj-labs/argocd/latest/docs/resources/application_set#nestedblock--spec--generator--list) in the `argocd_application_set` resource only supports an `elements` list.

We use the List generator's [elementsYaml feature](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-List/#dynamically-generated-elements) which is currently not supported.

### Potential Terraform Configuration

```hcl
  spec {
    generator {
      list {
        elementsYaml = "{{ .key.components | toJson }}"
      }
    }
...
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by perpective2410** [comment]
Any chance we could have this feature? cc: @the-technat 
We are able to deploy our applicationset with a kubernetes raw manifest and im not sure there is a way around without elementsYaml; Example

Here is an example of a working manifest. Not sure how to deploy it without elementsYaml since i'd like to create a list of elements dynamically based on the PR labels/tags

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-apps-pr
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - pullRequest:
              azuredevops:
                organization: bar
                project: foo
                repo: foo
                tokenRef:
                  secretName: azdo-pat-token
                  key: AZP_TOKEN
              requeueAfterSeconds: 10
          - list:
              elements: []
              elementsYaml: |
                {{- range .labels }}
                {{- $parts := splitList "/" . }}
                {{- if eq (len $parts) 2 }}
                - cluster: {{ index $parts 0 }}
                  chart: {{ index $parts 1 }}
                {{- end }}
                {{- end }}
  template:
    metadata:
      name: 'pr-{{ .number }}-{{ .cluster }}-{{ .chart }}'
      namespace: pr
    spec:
      project: core-apps
      source:
        repoURL: git@ssh.dev.azure.com/xxx
        targetRevision: '{{ .head_sha }}'
        path: '{{ .cluster }}/{{ .chart }}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        name: '{{ .cluster }}'
        namespace: pr
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

```
